# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_Stroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.IntegerField()),
                ('hold_time', models.IntegerField()),
                ('next_up_time', models.IntegerField(null=True)),
                ('next_down_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user_signature',
            old_name='attempt',
            new_name='total_time',
        ),
        migrations.AddField(
            model_name='user_signature',
            name='enter_pressed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_signature',
            name='tab_pressed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key_stroke',
            name='user_signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User_Signature'),
        ),
    ]
